export default {
  "flex-wrap": "flex-wrap: wrap",
  "flex-wrap-reverse": "flex-wrap: wrap-reverse",
  "flex-nowrap": "flex-wrap: nowrap",
  "float-right": "float: right",
  "float-left": "float: left",
  "float-none": "float: none",
  "flex-row": "flex-direction: row",
  "flex-row-reverse": "flex-direction: row-reverse",
  "flex-col": "flex-direction: column",
  "flex-col-reverse": "flex-direction: column-reverse",
  "clear-left": "clear: left",
  "clear-right": "clear: right",
  "clear-both": "clear: both",
  "clear-none": "clear: none",
  "box-border": "box-sizing: border-box",
  "box-content": "box-sizing: content-box",
  "object-contain": "object-fit: contain",
  "object-cover": "object-fit: cover",
  "object-fill": "object-fit: fill",
  "object-none": "object-fit: none",
  "object-scale-down": "object-fit: scale-down",
  "object-bottom": "object-position: bottom",
  "object-center": "object-position: center",
  "object-left": "object-position: left",
  "object-left-bottom": "object-position: left bottom",
  "object-left-top": "object-position: left top",
  "object-right": "object-position: right",
  "object-right-bottom": "object-position: right bottom",
  "object-right-top": "object-position: right top",
  "object-top": "object-position: top",
  "overflow-auto": "overflow: auto",
  "overflow-hidden": "overflow: hidden",
  "overflow-visible": "overflow: visible",
  "overflow-scroll": "overflow: scroll",
  "overflow-x-auto": "overflow-x: auto",
  "overflow-y-auto": "overflow-y: auto",
  "overflow-x-hidden": "overflow-x: hidden",
  "overflow-y-hidden": "overflow-y: hidden",
  "overflow-x-visible": "overflow-x: visible",
  "overflow-y-visible": "overflow-y: visible",
  "overflow-x-scroll": "overflow-x: scroll",
  "overflow-y-scroll": "overflow-y: scroll",
  "overscroll-auto": "overscroll-behavior: auto",
  "overscroll-contain": "overscroll-behavior: contain",
  "overscroll-none": "overscroll-behavior: none",
  "overscroll-y-auto": "overscroll-behavior-y: auto",
  "overscroll-y-contain": "overscroll-behavior-y: contain",
  "overscroll-y-none": "overscroll-behavior-y: none",
  "overscroll-x-auto": "overscroll-behavior-x: auto",
  "overscroll-x-contain": "overscroll-behavior-x: contain",
  "overscroll-x-none": "overscroll-behavior-x: none",
  "visible": "visibility: visible",
  "invisible": "visibility: hidden",
  "flex-1": "flex: 1 1 0%",
  "flex-auto": "flex: 1 1 auto",
  "flex-initial": "flex: 0 1 auto",
  "flex-none": "flex: none",
  "flex-grow-0": "flex-grow: 0",
  "flex-grow": "flex-grow: 1",
  "flex-shrink-0": "flex-shrink: 0",
  "flex-shrink": "flex-shrink: 1",
  "order-1": "order: 1",
  "order-2": "order: 2",
  "order-3": "order: 3",
  "order-4": "order: 4",
  "order-5": "order: 5",
  "order-6": "order: 6",
  "order-7": "order: 7",
  "order-8": "order: 8",
  "order-9": "order: 9",
  "order-10": "order: 10",
  "order-11": "order: 11",
  "order-12": "order: 12",
  "order-first": "order: -9999",
  "order-last": "order: 9999",
  "order-none": "order: 0",
  "justify-start": "justify-content: flex-start",
  "justify-end": "justify-content: flex-end",
  "justify-center": "justify-content: center",
  "justify-between": "justify-content: space-between",
  "justify-around": "justify-content: space-around",
  "justify-evenly": "justify-content: space-evenly",
  "justify-items-auto": "justify-items: auto",
  "justify-items-start": "justify-items: start",
  "justify-items-end": "justify-items: end",
  "justify-items-center": "justify-items: center",
  "justify-items-stretch": "justify-items: stretch",
  "justify-self-auto": "justify-self: auto",
  "justify-self-start": "justify-self: start",
  "justify-self-end": "justify-self: end",
  "justify-self-center": "justify-self: center",
  "justify-self-stretch": "justify-self: stretch",
  "content-center": "align-content: center",
  "content-start": "align-content: flex-start",
  "content-end": "align-content: flex-end",
  "content-between": "align-content: space-between",
  "content-around": "align-content: space-around",
  "content-evenly": "align-content: space-evenly",
  "items-start": "align-items: flex-start",
  "items-end": "align-items: flex-end",
  "items-center": "align-items: center",
  "items-baseline": "align-items: baseline",
  "items-stretch": "align-items: stretch",
  "self-auto": "align-self: auto",
  "self-start": "align-self: flex-start",
  "self-end": "align-self: flex-end",
  "self-center": "align-self: center",
  "self-stretch": "align-self: stretch",
  "min-w-0": "min-width: 0px",
  "min-w-full": "min-width: 100%",
  "min-w-min": "min-width: min-content",
  "min-w-max": "min-width: max-content",
  "min-h-0": "min-height: 0px",
  "min-h-full": "min-height: 100%",
  "min-h-screen": "min-height: 100vh",
  "font-sans": 'font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
  "font-serif":  'font-family: ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
  "font-mono": 'font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  "italic":  "font-style: italic",
  "not-italic": "font-style: normal",
  "text-left": "text-align: left",
  "text-center": "text-align: center",
  "text-right": "text-align: right",
  "text-justify": "text-align: justify",
  "underline": "text-decoration: underline",
  "line-through": "text-decoration: line-through",
  "no-underline": "text-decoration: none",
  "uppercase": "text-transform: uppercase",
  "lowercase": "text-transform: lowercase",
  "capitalize": "text-transform: capitalize",
  "normal-case": "text-transform: none",
  "truncate": "overflow: hidden; text-overflow: ellipsis; white-space: nowrap;",
  "overflow-ellipsis": "text-overflow: ellipsis",
  "overflow-clip": "text-overflow: clip",
  "align-baseline": "vertical-align: baseline",
  "align-top": "vertical-align: top",
  "align-middle": "vertical-align: middle",
  "align-bottom": "vertical-align: bottom",
  "align-text-top": "vertical-align: text-top",
  "align-text-bottom": "vertical-align: text-bottom",
  "whitespace-normal": "white-space: normal",
  "whitespace-nowrap": "white-space: nowrap",
  "whitespace-pre": "white-space: pre",
  "whitespace-pre-line": "white-space: pre-line",
  "whitespace-pre-wrap": "white-space: pre-wrap",
  "break-normal": "overflow-wrap: normal; word-break: normal",
  "break-words": "overflow-wrap: break-word",
  "break-all": "word-break: break-all",
  "border-collapse": "border-collapse: collapse",
  "border-separate": "border-collapse: separate",
  "table-auto": "table-layout: auto",
  "table-fixed": "table-layout: fixed",
  "appearance-none": "appearance: none",
  "select-none": "user-select: none",
  "select-text": "user-select: text",
  "select-all": "user-select: all",
  "select-auto": "user-select: auto",
  "resize-none": "resize: none",
  "resize-y": "resize: vertical",
  "resize-x": "resize: horizontal",
  "resize": "resize: both",
  "pointer-events-none": "pointer-events: none",
  "pointer-events-auto": "pointer-events: auto",
  "fill-current": "fill: currentColor",
  "stroke-current": "stroke: currentColor",
  "sr-only": `position: absolute;
width: 1px;
height: 1px;
padding: 0;
margin: -1px;
overflow: hidden;
clip: rect(0, 0, 0, 0);
white-space: nowrap;
border-width: 0;`,
  "not-sr-only": `position: static;
width: auto;
height: auto;
padding: 0;
margin: 0;
overflow: visible;
clip: auto;
white-space: normal;`,
  "bg-fixed": "background-attachment: fixed",
  "bg-local": "background-attachment: local",
  "bg-scroll": "background-attachment: scroll",
  "bg-clip-border": "background-clip: border-box",
  "bg-clip-padding": "background-clip: padding-box",
  "bg-clip-content": "background-clip: content-box",
  "bg-clip-text": "background-clip: text",
  "bg-bottom": "background-position: bottom",
  "bg-center": "background-position: center",
  "bg-left": "background-position: left",
  "bg-left-bottom": "background-position: left bottom",
  "bg-left-top": "background-position: left top",
  "bg-right": "background-position: right",
  "bg-right-bottom": "background-position: right bottom",
  "bg-right-top": "background-position: right top",
  "bg-top": "background-position: top",
  "bg-repeat": "background-repeat: repeat",
  "bg-no-repeat": "background-repeat: no-repeat",
  "bg-repeat-x": "background-repeat: repeat-x",
  "bg-repeat-y": "background-repeat: repeat-y",
  "bg-repeat-round": "background-repeat: round",
  "bg-repeat-space": "background-repeat: space",
  "bg-auto": "background-size: auto",
  "bg-cover": "background-size: cover",
  "bg-contain": "background-size: contain",
  "bg-none": "background-image: none",
  "bg-gradient-to-t": "background-image: linear-gradient(to top, var(--tw-gradient-stops))",
  "bg-gradient-to-tr": "background-image: linear-gradient(to top right, var(--tw-gradient-stops))",
  "bg-gradient-to-r": "background-image: linear-gradient(to right, var(--tw-gradient-stops))",
  "bg-gradient-to-br": "background-image: linear-gradient(to bottom right, var(--tw-gradient-stops))",
  "bg-gradient-to-b": "background-image: linear-gradient(to bottom, var(--tw-gradient-stops))",
  "bg-gradient-to-bl": "background-image: linear-gradient(to bottom left, var(--tw-gradient-stops))",
  "bg-gradient-to-l": "background-image: linear-gradient(to left, var(--tw-gradient-stops))",
  "bg-gradient-to-tl": "background-image: linear-gradient(to top left, var(--tw-gradient-stops))",
  "list-inside": "list-style-position: inside",
  "list-outside": "list-style-position: outside",
  "antialiased":  `-webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;`,
  "subpixel-antialiased":  `-webkit-font-smoothing: auto; -moz-osx-font-smoothing: auto;`,
  "normal-nums": "font-variant-numeric: normal",
  "ordinal": "font-variant-numeric: ordinal",
  "slashed-zero": "font-variant-numeric: slashed-zero",
  "lining-nums": "font-variant-numeric: lining-nums",
  "oldstyle-nums": "font-variant-numeric: oldstyle-nums",
  "proportional-nums": "font-variant-numeric: proportional-nums",
  "tabular-nums": "font-variant-numeric: tabular-nums",
  "diagonal-fractions": "font-variant-numeric: diagonal-fractions",
  "stacked-fractions": "font-variant-numeric: stacked-fractions",
  "transform": `--tw-translate-x: 0;
--tw-translate-y: 0;
--tw-rotate: 0;
--tw-skew-x: 0;
--tw-skew-y: 0;
--tw-scale-x: 1;
--tw-scale-y: 1;
transform: translateX(var(--tw-translate-x)) translateY(var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));`,
  "transform-gpu": `--tw-translate-x: 0;
--tw-translate-y: 0;
--tw-rotate: 0;
--tw-skew-x: 0;
--tw-skew-y: 0;
--tw-scale-x: 1;
--tw-scale-y: 1;
transform: translate3d(var(--tw-translate-x), var(--tw-translate-y), 0) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));`,
  "transform-none": "transform: none",
  "origin-center": "transform-origin: center",
  "origin-top": "transform-origin: top",
  "origin-top-right": "transform-origin: top right",
  "origin-right": "transform-origin: right",
  "origin-bottom-right": "transform-origin: bottom right",
  "origin-bottom": "transform-origin: bottom",
  "origin-bottom-left": "transform-origin: bottom left",
  "origin-left": "transform-origin: left",
  "origin-top-left": "transform-origin: top left",
  "transition-none": "transition-property: none",
  "transition-all":  `transition-property: all;
transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
transition-duration: 150ms;`,
  "transition":  `transition-property: background-color, border-color, color, fill, stroke, opacity, box-shadow, transform;
transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
transition-duration: 150ms;`,
  "transition-colors":  `transition-property: background-color, border-color, color, fill, stroke;
transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
transition-duration: 150ms;`,
  "transition-opacity":  `transition-property: opacity;
transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
transition-duration: 150ms;`,
  "transition-shadow":  `transition-property: box-shadow;
transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
transition-duration: 150ms;`,
  "transition-transform":  `transition-property: transform;
transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
transition-duration: 150ms;`,
  "border-solid": "border-style: solid",
  "border-dashed": "border-style: dashed",
  "border-dotted": "border-style: dotted",
  "border-double": "border-style: double",
  "border-none": "border-style: none",
  "place-content-center": "place-content: center",
  "place-content-start": "place-content: start",
  "place-content-end": "place-content: end",
  "place-content-between": "place-content: space-between",
  "place-content-around": "place-content: space-around",
  "place-content-evenly": "place-content: space-evenly",
  "place-content-stretch": "place-content: stretch",
  "place-items-auto": "place-items: auto",
  "place-items-start": "place-items: start",
  "place-items-end": "place-items: end",
  "place-items-center": "place-items: center",
  "place-items-stretch": "place-items: stretch",
  "place-self-auto": "place-self: auto",
  "place-self-start": "place-self: start",
  "place-self-end": "place-self: end",
  "place-self-center": "place-self: center",
  "place-self-stretch": "place-self: stretch",
  "ring-inset": "--tw-ring-inset: inset",
  "grid-flow-row": "grid-auto-flow: row",
  "grid-flow-col": "grid-auto-flow: column",
  "grid-flow-row-dense": "grid-auto-flow: row dense",
  "grid-flow-col-dense": "grid-auto-flow: column dense",
  "hidden": "display: none",
}
